#@ load("@ytt:overlay", "overlay")
#@data/values
---
#@overlay/match missing_ok=True
images:
  statsd_exporter: cloudfoundry/statsd_exporter-cf-for-k8s@sha256:f00b61db72a2e77bcca116e881251015209be7b2b1d1156ef7fc31fabe0b5f49
  uaa: cloudfoundry/uaa@sha256:8ab25d42d8a64519ccdcb5b57bafc1ac546d20a6bbcee09ff1b37c4c4811bf5d
