---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
  - name: bbl-state
  - name: identity-ci

outputs:
  - name: credential

run:
  path: identity-ci/shared/tasks/get-credential/task.sh

params:
  CREDENTIAL_NAME: ~
  BBL_STATE_DIR: ~
