---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfidentity/uaa-k8s-ci

inputs:
- name: uaa
- name: identity-ci

run:
  path: identity-ci/concourse/uaa-acceptance-gcp/tasks/run-k8s-template-tests/task.sh