---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfidentity/uaa-k8s-ci

inputs:
- name: uaa-k8s-release

run:
  path: uaa-k8s-release/ci/tasks/run-k8s-template-tests.sh
