resources:
- name: cf-for-k8s
  type: git
  source:
    # TODO change back to develop
    # branch: develop
    branch: 177656349-ci-pipeline
    private_key: ((cf_for_k8s_readonly_deploy_key.private_key))
    uri: git@github.com:cloudfoundry/cf-for-k8s.git
    ignore_paths:
      - ci

- name: cf-for-k8s-ci
  type: git
  source:
    # TODO change back to develop
    # branch: develop
    branch: 177656349-ci-pipeline
    private_key: ((cf_for_k8s_readonly_deploy_key.private_key))
    uri: git@github.com:cloudfoundry/cf-for-k8s.git

- name: uaa-k8s-release
  type: git
  source:
    # TODO change me back later
    # branch: main
    branch: 177656349-ci-pipeline
    private_key: ((uaa-k8s-release-read-write.private_key))
    uri: git@github.com:cloudfoundry/uaa-k8s-release.git

- name: uaa-k8s-release-ci-passed
  type: git
  source:
    # TODO change me back later
    # branch: ci-passed
    branch: 177656349-ci-pipeline-ci-passed
    private_key: ((uaa-k8s-release-read-write.private_key))
    uri: git@github.com:cloudfoundry/uaa-k8s-release.git

- name: uaa-k8s-release-except-images
  type: git
  check_every: 2m
  source:
    # TODO change me back later
    # branch: main
    branch: 177656349-ci-pipeline
    private_key: ((uaa-k8s-release-read-write.private_key))
    uri: git@github.com:cloudfoundry/uaa-k8s-release.git
    ignore_paths: [config/values/images.yml]

- name: uaa-github-release
  type: github-release
  source:
    owner: cloudfoundry
    repository: uaa
    access_token: ((cf_for_k8s_release_bot_access_token))

- name: uaa-docker-image
  type: registry-image
  source:
    repository: cloudfoundry/uaa
    username: ((dockerhub.username))
    password: ((dockerhub.password))
    tag: cf-for-k8s-ci-build

- name: ready-pool
  type: pool
  icon: pool
  source:
    uri: git@github.com:cloudfoundry/relint-ci-pools
    branch: main
    pool: k8s-dev/ready
    private_key: ((relint_ci_pools_readwrite_deploy_key.private_key))

- name: destroy-pool
  type: pool
  icon: pool
  source:
    uri: git@github.com:cloudfoundry/relint-ci-pools
    branch: main
    pool: k8s-dev/destroy
    private_key: ((relint_ci_pools_readwrite_deploy_key.private_key))

jobs:
- name: run-k8s-template-tests
  plan:
  - get: uaa-k8s-release-except-images
    trigger: true
  - get: uaa-k8s-release
  - task: run-k8s-template-tests
    file: uaa-k8s-release/ci/tasks/run-k8s-template-tests/task.yml

- name: build-uaa-image
  plan:
  - in_parallel:
    - get: cf-for-k8s
    - get: uaa-github-release
      trigger: true
      params:
        include_source_tarball: true
    - get: uaa-k8s-release

  - task: build-image
    privileged: true
    file: uaa-k8s-release/ci/tasks/build-uaa-image/task.yml

  - put: uaa-docker-image
    params:
      image: kbld-output/image.tar
      additional_tags: uaa-github-release/version

- name: validate-uaa-k8s-release
  public: true
  plan:
    - in_parallel:
        - get: uaa-k8s-release
          trigger: true
          passed: [ run-k8s-template-tests ]
        - get: uaa-docker-image
          trigger: true
          passed: [build-uaa-image]
        - get: cf-for-k8s
        - get: cf-for-k8s-ci

    - put: ready-pool
      params:
        acquire: true

    - task: display-cluster-info
      file: cf-for-k8s-ci/ci/tasks/display-gke-cluster-info/task.yml
      input_mapping:
        pool-lock: ready-pool
      params:
        GCP_PROJECT_NAME: ((ci_k8s_gcp_project_name))
        GCP_PROJECT_ZONE: ((ci_k8s_gcp_project_zone))
        GCP_SERVICE_ACCOUNT_JSON: ((ci_k8s_gcp_service_account_json))

    - task: bump-uaa-k8s-release-image-ref
      file: uaa-k8s-release/ci/tasks/bump-uaa-image-digest/task.yml

    - task: bump-uaa-k8s-release-in-cf-for-k8s
      input_mapping:
        uaa-k8s-release: updated-uaa-k8s-release
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: cloudfoundry/cf-for-k8s-ci
        inputs:
          - name: cf-for-k8s
          - name: uaa-k8s-release
        outputs:
          - name: updated-cf-for-k8s
        run:
          path: /bin/bash
          args:
            - -c
            - |
              set -euo pipefail

              pushd cf-for-k8s
                vendir sync -d config/uaa/_ytt_lib/uaa-k8s-release="../uaa-k8s-release"
              popd

              cp -r cf-for-k8s/* updated-cf-for-k8s/

    - task: install-cf
      file: cf-for-k8s-ci/ci/tasks/install-cf-on-gke/task.yml
      input_mapping:
        pool-lock: ready-pool
        cf-for-k8s: updated-cf-for-k8s
      params:
        GCP_SERVICE_ACCOUNT_JSON: ((ci_k8s_gcp_service_account_json))
        GCP_PROJECT_NAME: ((ci_k8s_gcp_project_name))
        GCP_PROJECT_ZONE: ((ci_k8s_gcp_project_zone))
        APP_REGISTRY_HOSTNAME: https://index.docker.io/v1/
        APP_REGISTRY_REPOSITORY_PREFIX: ((cf_for_k8s_private_dockerhub.username))
        APP_REGISTRY_USERNAME: ((cf_for_k8s_private_dockerhub.username))
        APP_REGISTRY_PASSWORD: ((cf_for_k8s_private_dockerhub.password))
        DOMAIN: k8s-dev.relint.rocks

    - task: run-smoke-tests
      file: cf-for-k8s-ci/ci/tasks/run-smoke-tests/task.yml
      attempts: 2
      params:
        SMOKE_TEST_SKIP_SSL: false

  on_success:
    do:
      - task: delete-cf
        file: cf-for-k8s-ci/ci/tasks/delete-cf/task.yml
        input_mapping:
          pool-lock: ready-pool
        params:
          GCP_PROJECT_NAME: ((ci_k8s_gcp_project_name))
          GCP_PROJECT_ZONE: ((ci_k8s_gcp_project_zone))
          GCP_SERVICE_ACCOUNT_JSON: ((ci_k8s_gcp_service_account_json))
      - put: destroy-pool
        params:
          add: ready-pool
      - put: ready-pool
        params:
          remove: ready-pool

- name: bump-image-in-uaa-k8s-release
  serial: true
  plan:
    - in_parallel:
      - get: uaa-k8s-release
        trigger: true
        passed: [validate-uaa-k8s-release]
      - get: uaa-docker-image
        trigger: true
        passed: [validate-uaa-k8s-release]

    - task: bump-uaa-k8s-release-image-ref
      file: uaa-k8s-release/ci/tasks/bump-uaa-image-digest/task.yml

    - put: uaa-k8s-release
      params:
        merge: true
        repository: updated-uaa-k8s-release

    - put: uaa-k8s-release-ci-passed
      params:
        repository: updated-uaa-k8s-release
